#!/bin/bash
# Joachim Geserick
# In order from master Kano Joerg Schirottke
# This was his idea
# sshvs "Screen Size Horizontal Vertical Sync"

# fix-res() is copyrighted by Jörg Schirottke <master@kanotix.com>
# 2005-08-18 extensively modified by Stefan Lippers-Hollman <s.l-h@gmx.de>
# licensed under the GPL

PATH="/usr/sbin:$PATH"
MENUGEOMETRY="250x250+500+250"
MENUGEOMETRY2="250x100+500+250"
ICON="randr"
PROGRAM="change-res"
X_CONF="/etc/X11/xorg.conf"
ATIME=$(date +%d.%m.%y-%H:%M)

KANOTIXSU=$(type -p kanotix-su)	|| KANOTIXSU="/usr/bin/kanotix-su"
KDIALOG=$(type -p kdialog)	|| KDIALOG="/usr/bin/kdialog"
PERL=$(type -p perl)		|| PERL="/usr/bin/perl"
FIXRES=$(type -p fix-res)	|| FIXRES="/usr/sbin/fix-res"

KMENU="$KDIALOG --icon $ICON --geometry $MENUGEOMETRY --caption $PROGRAM --menu"
KCOMBOBOX="$KDIALOG --icon $ICON --geometry $MENUGEOMETRY2 --caption $PROGRAM --combobox"
KWARNINGYESNO="$KDIALOG --icon $ICON --title $PROGRAM --warningyesno"
KINPUTBOX="$KDIALOG --caption $PROGRAM --inputbox"
KMSGBOX="$KDIALOG --icon $ICON --title $PROGRAM --msgbox"
KYESNO="$KDIALOG --icon $ICON --title $PROGRAM --yesno"


for i in "$KANOTIXSU" "$KDIALOG" "$PERL" "$FIXRES"; do
	if [ ! -x "$i" ]; then
		echo "$i: missing, terminate abnormally."
		exit 999
	fi
done

if [ "$UID" -ne 0 ]; then
	[ -x "$KANOTIXSU" ] && exec "$KANOTIXSU" "$0" "$@"
	
	echo Error: You must be root to run this script!
	exit 1
fi

bailout() {
	exit 1
}

exitus() {
	#echo "Have fun."
	exit 0
}

menu() {
	choice=$($KMENU "Display Settings" \
		"info"		"Info " \
		"scsize"	"Screen Size" \
		"horivertsync"	"Scanning Frequenz" \
		"noml"		"NOML (delete all Modelines)" \
		"about"		"About" \
		"exitus"	"Exit")
	
	case "$?" in
		0)
			cp "$X_CONF" "$X_CONF-$ATIME.save"
			"$choice"
			;;
		1)
			bailout
			;;
	esac
}

scsize() {
	xss2=$($KCOMBOBOX "Set Screen Size" \
		"640x480" \
		"800x600" \
		"1024x768" \
		"1152x864" \
		"1280x1024" \
		"1400x1050" \
		"1600x1200")

	if [ $? = 0 ]; then
		$KWARNINGYESNO "Set screen-size at $xss2?"

		if [ "$?" = 0 ]; then
			$KMSGBOX "$(fix-res "$xss2")"
		fi
	fi

	menu
}

noml() {
	$KWARNINGYESNO "Delete all Modelines?"

	if [ $? = 0 ]; then
		"$PERL" -pi -e 's/(Mode.ine.*\n)/#\1/' "$X_CONF"
	fi

	menu
}

horivertsync() {
	$KYESNO "It's a \"TFT\" ?"
	if [ "$?" = 0 ] ; then
		horivertsync_tft
		else
		horivertsync_crt
	fi
	menu
}

horivertsync_crt() {
	HORIZSYNC=$($KINPUTBOX "Horizontal Frequenz" "30 - 65")
	VERTREFRESH=$($KINPUTBOX "Vertical Frequenz" "50 - 75")

	$KWARNINGYESNO "Write New Horizontal Frequenz: $HORIZSYNC and New Vertical Frequenz: $VERTREFRESH?"

	if [ "$?" = 0 ] ; then
		"$PERL" -pi -e "s/^(\s*HorizSync).*/\1\t$HORIZSYNC/" "$X_CONF"
		"$PERL" -pi -e "s/^(\s*VertRefresh).*/\1\t$VERTREFRESH/" "$X_CONF"
	else 
		echo stop
	fi
}

horivertsync_tft() {
	HORIZSYNC=$($KINPUTBOX "Horizontal Frequenz" "31 - 65")
	VERTREFRESH="60"

	$KWARNINGYESNO "Write New Horizontal Frequenz: $HORIZSYNC"

	if [ "$?" = 0 ] ; then
		"$PERL" -pi -e "s/^(\s*HorizSync).*/\1\t$HORIZSYNC/" "$X_CONF"
		"$PERL" -pi -e "s/^(\s*VertRefresh).*/\1\t$VERTREFRESH/" "$X_CONF"
	else 
		echo stop
	fi
}

info()
{
	$KMSGBOX "Before you do anything, save settings ($X_CONF). After the settings you must restart the X-Server.
		The original-script is fix-res from Master Kano
		see http://forum.kanotix.net/search.php.
		WARNING: this GUI is not save for dual head setups."
	
	menu
}

about()
{
	ENABOUT="$PROGRAM is licensed under the GPL
		Authors:\nJörg Schirottke\nJoachim Geserick\nStefan Lippers-Hollmann
		The script is meant to be 'experimental', no warranties implied!
		Any use of the script is at your own risk!
		NOTE: this version of $PROGRAM is an inofficial (modified) release of sshvs \
		(www.jgese.de) and thus may have bugs that are not present in the original \
		version. Please send bug reports and support requests to the Kanotix project.
		The original author should not be bothered with problems of this version."
	DEABOUT="$PROGRAM unterliegt der GPL
		Autoren:\nJörg Schirottke\nJoachim Geserick\nStefan Lippers-Hollmann
		Das Script ist experimentell, wir übernehmen keinerlei Garantie!
		Das Verwenden geschieht auf eigene Verantwortung!
		Hinweis: Diese Version von $PROGRAM ist ein inoffizielles (modifiziertes) \
		Release von sshvs (www.jgese.de) und kann demzufolge Fehler aufweisen die \
		nicht in der offiziellen Version auftreten. Bitte senden Sie Bugreports und \
		Supportrequests an das Kanotix Projekt.
		Der ursprüngliche Autor sollte nicht mit Problemen \
		dieser Version belästigt werden."
	
	case "$LANGUAGE" in
		de*|at*|ch*)
			$KMSGBOX "$DEABOUT"
			;;
		*)
			$KMSGBOX "$ENABOUT"
			;;
	esac

	menu
}

menu

